### ISSUE TITLE
Preparation 1 Issue

### ISSUE THREAD

**Issue by dykesb** [gvsu-sta518/community#1]
Learning during a pandemic is difficult.
Teaching during a pandemic is also difficult! Share a story from the past year of a silly technology issue that you did or witnessed.
I'll start things off:

I taught a Saturday 9 am - noon 😭 Intro Stat course. I found out that if my partner used the microwave during this time, the internet completely disappeared in my office - I had just started to introduce an activity and then everything failed to load. Needless to say, I was *extremely* anxious.

**Comment by LeviRosendall** [comment]
Over the summer, I worked remotely which was fine *most* of the time.
Unfortunately, I was at home and several of my nieces and nephews were there as well, and no matter how far away I went you could still hear them \
 \
**VERY**  
\
well, so that meeting included me being muted almost all of the time. At the end my supervisor asked me if I was babysitting lol

**Comment by nhroesler** [comment]
I took a summer class this year. First day of class I had forgotten to *disconnect* my laptop from the Bluetooth speaker downstairs, so my roommate and her parents had to listen to my professor introduce himself progressively **louder** since I was panicking and trying to turn the volume up. I only realized what I was doing after hearing his voice coming from all the way downstairs. Whoops.

Sorry Rebecca. Sorry Rebecca's mom.

**Comment by AverySmithson** [comment]
During my internship over the summer I was required to have my video camera on for most of my meetings. There was this little tab that I could pull to put like a cover of sorts over the camera. I must have done that *accidentally* and I was convinced my camera was **broken**. Turns out all I had to do was click the little tab back into the correct place. It took me forever to realize that dumb mistake.

**Comment by keydels** [comment]
I was at work and my supervisor set up a meeting with me and a manager from a different department via WebEx to talk about different job opportunities. I had never used WebEx before and was **nervous** for the meeting in general and when we connected I couldn't hear her. I was sending chats to her letting her know and we tried reconnecting *at least* 5 times until I realized my volume was just turned all the way down. Oops....

**Comment by simonsab** [comment]
Prior to my current job, most of the pandemic I was doing software support over the phone for a small start-up. Our clients were campground/resort owners. It was a lot of older people and one of our regular callers reached out to make a feature request to our devs regarding how annoyed she was that she had to *restart her computer every time she needed to switch users on the **web-based** software*. 
She had been using our software for over a year, **literally** shutting down her computer every time someone else needed to login...

**Comment by murillocGVSU** [comment]
During my internship earlier this year when I was going to meet my to-be manager for the first time, I connected to the meeting but was met with a black screen for myself. After **persistent** attempts I failed to realize that my camera had a cover on it. I described it as *technical difficulty*.

**Comment by ian-curtis** [comment]
At the beginning of the pandemic when everything was just getting shut down, I had a bad habit of not muting my microphone (or forgetting to do so after I was done speaking). On many occasions the class could hear my siblings yelling or arguing but that was quiet. However, there was a time when my dog, who loves to sleep on a small futon near my desk, decided she was done napping, stood up, and did the downward dog thing dogs do. While she was doing that, she made the loudest ***YEOWWWW*** (I guess the dog version of an early-morning stretch and yawn?). It took a minute for everyone to realize that no, it was not me who had made that noise, but my dog who was already on her way out of the room. 

Below is an image of Sadie, the innocent yeow-er. (If you ever need dog pics, just let me know. I have tons :D).

![Image of my goldendoodle, Sadie](https://i.imgur.com/2uSnJwb.jpeg)

(Can also be found [here](https://imgur.com/gallery/ncHEcZm) if the image doesn't work right for you.)

**Comment by lcadagin** [comment]
## Forgetting to Mute

Last fall I was sitting in on a **big** Skype conference call at work.  I had just joined a new team and introduced myself to my director others on the line at the very beginning.  I had nothing to contribute for the rest of the meeting.  I stayed on the line and started doing other work.  In the middle of the meeting I started playing an Eagles song very loudly, forgetting that I did not go back on mute.  All of a sudden a lot of my coworkers started signing along and I realized my mistake.  I quickly shut off my music and apologized to *everyone*.

**Comment by manapradit** [comment]
#### Wifi issue
My wifi had been working well until this summer, I noticed the issue when I continually lost the wifi signal and the router kept restarting. What is worse is, the issue is getting worse in the past few weeks. I can barely connect to the internet especially in the morning and late at night.  I hope my wifi does not catch <span style="color:red">some COVID text</span> ***and it gets better soon!***

**Comment by cunhag** [comment]
I was working at the hospital as a Nurse Technician and taking only one class the semester when the pandemic *first* started. Although my job did not go online, my class had to go online for half of the semester. After a long night working at the hospital, I got home for my zoom class and the professor had asked me a question and after a long answer talking I realized that I was on mute the **entire** time.

**Comment by TylerToren** [comment]
Last year, I took an online class called Ethics in Business. Someone must have left their microphone on, because while the professor was lecturing us, we heard a loud voice say, "That **$#&@!** doesn't know what she's talking about". Then the professor replied, "**YOU BETTER NOT BE TALKING ABOUT ME!**" and I'm pretty sure the whole class burst out laughing.

**Comment by mahmisab** [comment]
# Technology Sucks on a Golf Course
Over the summer, I worked at a golf club as a bev cart girl. There were _many_ times where the iPad I was using would drop its connection to the wifi and I'd have to zoom back to the clubhouse to connect back. Luckily, not too many golfers were annoyed.

**Comment by elaynast** [comment]
*Once upon a time* I took a class last year where we often were put into break out groups. This class was early in the morning and I often attended while still laying in my bed. One morning, my classmate in my group was having trouble sharing his screen for the group and accidently clicked another button that turned my camera on. The other team members saw me laying in bed with cereal on my lap for about 3 seconds until I turned the camera back off. It was **not**  a great moment.

**Comment by arepesh** [comment]
*When the pandemic first started*, my family had to start working from home. My sister and I were both finishing up the school year and my dad had to work from home as well. My dad didn't like using the home computer so he decided to bring his work computer home and set it up at the **kitchen table**. So any time my dad had to work we had cables running through the house so he could connect to the router. So we were constantly tripping over wires.

**Comment by ferkullj** [comment]
My current laptop is ancient and/or just not great compared to most. Sometimes I had 10 minutes between an online class and an in-person class last year which meant using my laptop on campus for the online class. It often failed to load programs or documents being shared by my professor, so I spent a lot of time smiling and nodding during lectures and having to try it all again *after* lecture since I couldn't really follow along.
![Fine]("https://giphy.com/embed/9M5jK4GXmD5o1irGrF" width="419" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/this-is-fine-9M5jK4GXmD5o1irGrF">via GIPHY</a></p>)

**Comment by proctorlauren** [comment]
This past spring my roommate got sick with COVID, so my other roommate and I had to quarantine together in our apartment. After figuring out all of the details with how I would attend class virtually again, we started to have **horrendous** wifi issues. I started to panic when I realized that I NEEDED the wifi in order to attend class, and I could not go somewhere else because I was in quarantine! After days of internally (and externally) freaking out, I realized I could just order a new router.😐 Needless to say, the wifi issue was fixed and we did not have any additional wifi issues! 
![Image](https://media.giphy.com/media/pynZagVcYxVUk/giphy.gif?cid=ecf05e473dioa3nx6h26rxjedsf3tyfe7nbon7h0xqvje55r&rid=giphy.gif&ct=g)

**Comment by VanDykN** [comment]
Many older people at my job had never video conferenced before there was many foreheads and close up on *glasses* while the **yelled**  at the computer screens until we got settings worked out on their head phones.

**Comment by dahalkush** [comment]
I did not have such a lot of experience in online tutoring at the covid time. While taking the *classes*, i usually failed to **turn off the mic** in the begining of pandemic. I lived in a joint family so there were background noises every time.  So most of the time others in the meet used to complaint about my background noise. That was the problem i faced during the start of the pandemic.

**Comment by Snowballtheblackcat** [comment]
The power went off at my house for several days so I had to walk about a mile to the nearest boba cafe to hook up to wifi and charge all my devices. This was extremely important because I was also taking a summer course, with my final exam being the day after we lost power :(

**Comment by gichukia** [comment]
Well, *I have not had any issues with online sessions.* However, one time my roommate pretended his camera was not working because his room was a hot mess, haha. Also, there was a time a colleague forgot to mute herself, and we could hear her talking in her **mother tongue.**

**Comment by coourtneyrose** [comment]
My professor virtually met with each student at the end of the semester to take an oral exam. We all scheduled on a Google calendar. When you schedule appointments on Google calendar, it automatically sends a Google Meet link for that time. So I figured that the meeting was on Google Meet....it was **not**. Apparently, we were supposed to meet on Blackboard Colloborate despite the link for the Google Meet being sent directly to us. Oops.

![Image](https://media0.giphy.com/media/ISOckXUybVfQ4/giphy.gif?cid=ecf05e47ttmnqcx09wjeby7f0pzg80g90pgv2shippfj3a9m&rid=giphy.gif&ct=g)

**Comment by bowerash** [comment]
<p>I was fortunate enough **not** to have any issues with wacky virtual learning problems last semester. However, I only had two classes so I consider myself pretty lucky in that aspect. <br>Probably the only issue I really had was with collaborating with my team on a project. We ended up having a lot of conference calls because BB Collaborate refused to work for us.</p>

**Comment by nash-meg** [comment]
Last year in one of my online classes, my professors mic started to randomly make her sound like a *robot*\
It was very freaky the first time, but every time after (it happened **several** times lol) we would just tell her "you're in Darth Vader mode again"\
![Image](https://media.giphy.com/media/ZX6NHzA9Fcddm/giphy.gif)

**Comment by damosack** [comment]
I only took two classes last year (one each semester) so I experience anything *too* annoying, but I did have one class where the professor's wifi wasn't so good and it seemed like whenever he started explaining something that was confusing he'd start staring at us all with that droopy-eyed, open mouth expression a bad internet connection always seems to catch you in. I kinda felt bad for him, having to repeat things so much, but we all got there eventually.

unrelated but here's a picture of my cute lil doggo 
![IMG_3997](https://user-images.githubusercontent.com/89871053/131716172-ea9cec38-54a4-49d9-9a33-269bb03884c2.JPG)

**Comment by SSterling7** [comment]
My jobs and classes have been fully online since covid started- my wifi **NEVER** works right. Almost every meeting I have over zoom it glitches or the sounds out or I get kicked off or *something*...

**Comment by BruceBuurstra** [comment]
One silly technology issue that I had recently was that my computer screen had something wrong with it where my screen would fade out and have vertical lines across the entire screen which was not fun to look at but I could still see my screen slightly. Also my screen would start out fine when I started my computer but after it would fall asleep then the screen would have the issue. In one of my zoom classes this summer I would watch the class but not actually be moving my mouse on my computer. That class I think my computer fell asleep and I had to restart it to get the screen fixed **3 times** before I adjusted my computer settings to not fall asleep right away *and then* I went and got a new screen put on.

**Comment by spradeko** [comment]
# Direct ethernet connection to PC or decent wifi in the rest of the apartment?

I had moved into an apartment earlier this year and the wiring for the internet connection led to the front living room. This made a lot of sense considering I spent most of the time in the dining/living room watching media, working, etc. **However**, I decided that a direct ethernet connection would be very beneficial to have in the back of the house where my PC was set up. I proceeded to reconnect the wires to the back of the apartment and in turn made the front rooms pretty terrible for wifi. 

![image](https://www.cnet.com/a/img/gw3zsHSUTpgK5oG4GdH5_UvpRxM=/109x127:1440x873/1092x614/2019/05/22/1b710a6b-5f4d-4987-a046-c23674b221a3/picard-meme-facepalm.jpg)

**Comment by sarbauprety** [comment]
The major issue for me while learning online was the internet connection as I used to get disconnected a lot. Also, the background noises sometimes when I needed to turn my mic on as I lived near a factory!

**Comment by owaiskhanafridi** [comment]
Following are the issues I had to face during this pandemic:

- Internet connectivity issues
- Tasks took longer than in-person collaboration
- Gained some extra pounds
- No travelling

![](https://media.giphy.com/media/58FMysL4cmjsIales5/giphy.gif)

**Comment by Janet15** [comment]
I was taking a software development course and I would **constantly** forget to connect my computer to power so it would switch off _suddenly_ in the middle of class/meetings and I would disappear even in the middle of conversations.
[!](https://media.giphy.com/media/l0MYPh8gSCntZTsdO/giphy.gif)

**Comment by snydeaus** [comment]
During one of my classes in the winter semester of this year, the professor taught the **WHOLE** class with the camera just facing her while she was writing notes down. Everyone was afraid to speak up so we all just sat behind our computers and listened. She found out the next class day and asked everyone why they didn't speak up...
![Image](https://media.giphy.com/media/jOpLbiGmHR9S0/giphy.gif)

**Comment by BryanJacques** [comment]
Even though I had physically muted my *mic* while on a meeting, I didn't know that it played sounds of video played on my computer. Somehow broadcasted audio of youtube video just to let everyone know I wasn't paying attention. At least it was only [Jomez](https://www.youtube.com/channel/UCmGyCEbHfY91NFwHgioNLMQ).

**Comment by connormcnamee** [comment]
**WIFI went out at the worst possible time**

I had a professor last year who made our final exams giving a group presentation to the class, but the last part of the fall 2020 semester was all online. So I had to give the presentation online by sharing my screen. That ended up being too much for my home WIFI to handle and it went out in the *middle* of the presentation. I had about 5 minutes of panic while I tried to get it working again.

**Comment by vinaybommireddy** [comment]
This incidence occurred while I was undergoing classroom session. It was both awkward and funny. Because the iPhone taptic engine technology overheard one of my **friends question** to the trainer, Siri replied, I'm sorry, I don't understand what you just said. *Everyone in the room burst out laughing.*

**Comment by khizerkhan1992** [comment]
I am an international student. I came here so it will be the exchange of culture but when I came here everything was close, so I spend my first year of graduation in my room.

**Comment by asimot** [comment]
Over the summer I had the opportunity to intern at _SpartanNash_ as an IT applications intern, working closely with the master data management team and the IT architecture team.  This was a __great__ experience with huge learning opportunities for me with IT and MDM tools!

**Comment by lindsaybandyk** [comment]
On my an exam I had a group zoom set up for my Organic Chemistry class and I had forgotten that even if I had my volume off I was not muted. Basically I was singing until my professor flagged me in the chat for the 5th time. It was probably 30 minutes into the exam.

**Comment by debit7** [comment]
During Pandemic, I used to do WFH and must be online and 24/7 work as we are at home and always *Available*. **Literally** there was no personal space.
