### ISSUE TITLE
Preparation 3: Object 'mpg' not found

### ISSUE THREAD

**Issue by bowerash** [gvsu-sta518/community#13]
I am trying to follow along with the book to create the mpg scatterplot and I keep getting an error that the mpg dataset could not be found. However, I was able to pull the dataset above my code. 

At first, I was concerned I was typing something incorrectly so I tried to copy the code from the book but this has not seemed to correct the problem. 

Is there something wrong with the way that I am formatting the function or am I missing a call function before the textbook-provided code?  

![mpg](https://user-images.githubusercontent.com/89888090/133000971-7b8c3201-09db-4c7d-8b4b-39b5b92cb5ae.PNG)

**Comment by simonsab** [comment]
@bowerash Not 100% sure, but I think you have an erroneous "ggplot2" in your code. 
Try:
`ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))`
If you are writing/running your code in the console, it may also help just for editing purposes (i.e. testing specific lines) to write in a script instead. Hard to know for sure from your photo though, so disregard if not applicable.

**Comment by dykesb** [comment]
You are getting the "`object 'mpg' not found`" error because the `package::...` method does not follow the [distributive property](https://en.wikipedia.org/wiki/Distributive_property). That is, if you do not fully load a package into your environment (e.g., `library(ggplot2)`), you will have to use `package::` prior to each item from that package. So, you would need to either load `{ggplot2}` into your environment or your updated code would need to be:

```
ggplot2::ggplot(data = ggplot2::mpg) + geom_point(mapping = aes(x = displ, y = hwy))
```
