### ISSUE TITLE
Solutions for Activities

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#25]
Would it be possible to post the solutions for all activities? I usually don't get to the last question or two in class and would like to make sure I'm getting the right idea.

Sorry if they are posted somewhere and I missed them.

**Comment by dykesb** [comment]
Can I propose an alternative idea? Instead of me posting a solution, we use this `community` space to post confusing items, "why is this not producing results?" items, etc. I want to provide feedback and ask clarifying questions as you find solutions - not seeing my solution and people thinking, "that's the only way to do *x*." I think directed feedback on your individual work would be more beneficial.
