### ISSUE TITLE
Activity 5: Boxplot X-Axis and Jitter Question

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#28]
I'm thinking my major boxplot is not looking how it's intended to. Can I clean up my x-axis or use jitter differently?
![image](https://user-images.githubusercontent.com/89871886/135547175-33903625-634f-4a01-b57d-0da7c369c56b.png)
![image](https://user-images.githubusercontent.com/89871886/135547303-9ea4e220-75ec-46a1-aa30-9eb8bab87653.png)

**Comment by dykesb** [comment]
A couple of thoughts:

- To better view the x-axis labels, you could flip your x and y variables (i.e., `x = median_med_earnings, y = major_category`). Additionally, since you have `aes(x = major_category, y = median_med_earnings)` in both `geom_` layers, you could move this up to the `ggplot` call so that you only have to type that information once (leaving `aes(color = major_category)` in your `geom_boxplot` layer.
- In this, you are only plotting the median of median earnings (one value for each major category). Remember that boxplots need at least 5 data values. I do not think you need to do the `group_by` or `summarise` prior to plotting to do what you are wanting to accomplish.
