### ISSUE TITLE
Day 13 Agenda

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#39]
I wasn't sure about the values associated with the format argument in knitr::kable(). It says that for .Rmd's it uses the "pipe" format by default. Would it be good to know what the simple, latex, html, and rst options are as well?

**Comment by ian-curtis** [comment]
I really enjoyed this preparation. I love making fun visualizations of data. However, I got a little frustrated because I had to look up every single function I wanted to use. However, I am used to this now and know that the more I use `kable` and `{kableExtra}`, the more familiar I will be with them.
