### ISSUE TITLE
Preparation 2: Files not showing in GitHub

### ISSUE THREAD

**Issue by proctorlauren** [gvsu-sta518/community#5]
I am completing the preparation02 assignment and I am having some issues. I got to the very last step and my preparation02-file.R file is not in my preparation02 repository. I have tried to redo some of the steps and have gotten a few errors and now I am just a bit lost. Does anyone know where the issue could be? Thanks!

**Comment by dykesb** [comment]
I forgot to include the following line at the end of Task 5:

> To update GitHub with these changes, in the Git pane of RStudio click on ![push-icon](https://user-images.githubusercontent.com/40521287/132129966-788d8b04-4138-4980-8b06-61b1ed662445.png) Push.

Also, I realized Task 4 and Task 5 are named the same thing (oops - copy-paste, then forgot to edit). Task 5 should be named "Create, Edit, Commit, and Push"

**Comment by proctorlauren** [comment]
I did click on push and got this error message: "Support for password authentication was removed on August 13, 2021. Please use a personal access token instead." Do I need to start over with all of these steps?

**Comment by dykesb** [comment]
Anytime you are asked for your GitHub password in RStudio (e.g., you might get a pop-up window when you try to push), you should supply your PAT (not your GitHub password). If you still have access to your PAT, try closing your `preparation02` RStudio Project, then reopening it:

1. In your RStudio Project, click on the orange power icon in the upper-right hand corner, 
2. You should now be at the RStudio Workbench main screen, click on `preparation02` on the **Projects** side (right-hand side).
3. Try pushing again and supply your GitHub username and PAT when prompted for username and password, respectively.

If you no longer have access to your PAT, you should only need to complete Task 3 (along with `library(usethis)` prior to `create_github_token()`) to obtain a new PAT. Then, you can push (since you've already committed) and provide your GitHub username and new PAT.

**Comment by proctorlauren** [comment]
This worked and I've got it all figured out! Thank you!!

**Comment by lcadagin** [comment]
This worked for me as well, thank you very much!

**Comment by ravichag** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/89947557/132543184-4d5d0f3b-cebf-48db-8a47-558095eb29a1.png)
 it is showing this error message while doing commit and it is not showing my file even though i tried pushing the file. what should i do?

**Comment by Luttrell6048** [comment]
<img width="1280" alt="Screen Shot 2021-09-08 at 12 26 17 PM" src="https://user-images.githubusercontent.com/89804948/132547941-f6a3a603-dcc6-49e6-b2ee-24aec7e76189.png">

I seriously haven't a clue. First my R file did not show, so I created a new token. Then this started to pop up instead.
