### ISSUE TITLE
Day 20 Agenda

### ISSUE THREAD

**Issue by LeviRosendall** [gvsu-sta518/community#55]
I started a Day 20 Agenda.

I think the muddiest thing for me was knowing what to look for for the 2 document creation packages. I'm sure there are a lot of things, but the stuff I found seemed to be underwhelming. I'd love to know if there is a library with packages about document creation.

**Comment by ferkullj** [comment]
The reactive graphs were pretty confusing to me. The very simple ones were easy to follow, but it got overwhelming when there were arrows going everywhere. I'm not sure how to look at Shiny code and know the order in which the code executes.

**Comment by coourtneyrose** [comment]
Are there any other really good explanation videos about Shiny apps that are a little shorter than Jesse Mostipak's videos? Just a quick google search brings up a ton of them, but has anyone had success with any that they could recommend?

**Comment by dykesb** [comment]
Videos beyond Jesse's are:

- [Dr. Lendway and her two teaching assistants](https://www.youtube.com/watch?v=ak_NJCVrJXY) create a simple app in 43 minutes.
- [Dr. Garrett Grolemund](https://shiny.rstudio.com/tutorial/#watch) did a 2 hour 25 minute workshop a few years ago, but there are links below the player to different sections.
- Not a video, but 40 examples from [Zev Ross and his team](http://zevross.com/blog/2016/04/19/r-powered-web-applications-with-shiny-a-tutorial-and-cheat-sheet-with-40-example-apps/)
- A recent workshop from [Mike Garcia](https://www.youtube.com/watch?v=eoeLn8SyDW8) at `rstudio::global(2021)` (1 hr 18 mins)

Interested to see what others have found helpful!

**Comment by lcadagin** [comment]
The muddiest part for me was getting my head around when to use observeEvent() and eventReact().  This was not totally clear to me in the reading and activities.

**Comment by proctorlauren** [comment]
The muddiest part for me was understanding the reflection honestly. Did this mean documents like Beamer presentations and dashboards? I read about those and some others, but I was just unclear about what it meant in the reflection. I also just think the Shiny App coding is going to have to be something that takes some time to get down!

**Comment by ian-curtis** [comment]
I am starting to see the connections between the `ui`, the `server`, and the app itself. However, reactive expressions are confusing in general and I am struggling to see the differences between the various server options. Namely, `isolate`, `observeEvent`, `reactive`, `eventReactive`, and `observe` are all very similar in my head. I can not confidently determine when I might want to use each one. I really only knew for the activities because the instructions said I might want to use one or the other. The Shiny cheatsheet is helpful in this regard, but I feel like if I don't understand the true functions of these expressions, then the cheatsheet can only do so much.
