### ISSUE TITLE
Choropleth Issues 

### ISSUE THREAD

**Issue by elaynast** [gvsu-sta518/community#64]
Howdy!
I am currently trying to make a choropleth map of Michigan by county for my final project with the fill= Proportion of people tested for high lead levels. I have the initial map separated by counties, but when I try to put the proportions over it, I get an error. Here is the code and error for reference:
![image](https://user-images.githubusercontent.com/89864972/143989141-ebaf9fde-5e21-46b1-b793-ca7f8d5ea3da.png)
![image](https://user-images.githubusercontent.com/89864972/143989211-967b1550-d52c-452f-abd3-bc4261190bcf.png)
I'm not really super sure exactly what it means or how to create a sf column, but if anyone has an idea to put me in the right direction I would really appreciate it!

**Comment by dykesb** [comment]
I think you need to provide a `geometry` argument in your `geom_sf` aesthetics. C Claus Wilke provides two workarounds [here](https://github.com/tidyverse/ggplot2/issues/3936#issuecomment-891161329). However, pay attention to how his shapefile (`US_counties`) and value-to-plot file (`US_census`) are organized when comparison to your files.

Aside, Claus used [`{repex}`](https://reprex.tidyverse.org/) to create these **rep**roducible **ex**amples that provide code (instead of images) so users can try it on their own machines. The Articles menu would be a good place to see examples of how to use this package.

**Comment by elaynast** [comment]
I looked at the example and I'm still a little confused because I think that I have the order of the join correctly using the geometric data (michigancounty) first. I also tried the geometry=geometry option and got this error:
![image](https://user-images.githubusercontent.com/89864972/144094573-21f6d902-8976-4a18-abcd-257e6f4f1b72.png)
Here's more of my code from the join in case it's something really obvious that I'm just not seeing
![image](https://user-images.githubusercontent.com/89864972/144094477-4550f61c-3c09-4a7e-87ba-03736c6edc1f.png)
Thank you!

**Comment by dykesb** [comment]
`geometry` would need to be done within an aesthetic call as you are assigning a variable to it. I also think this needs to be in your `geom_sf` layer. However, this depends if 1) your dataset has a column called `geometry` and 2) your `geometry` column is a nested list/dataframe of longitudes and latitudes.
